import { test,expect } from '@playwright/test'
import fs from 'node:fs/promises'
import path from 'node:path'
import { zipSync,strToU8 } from 'fflate'
const fixture=(f:string)=>path.resolve('tests/fixtures/'+f)
test('reading, search, theme, mobile and keyboard',async({page})=>{
 const requests:string[]=[];page.on('request',r=>requests.push(r.url()))
 await page.goto('/');await expect(page.getByRole('heading',{name:'学习札记',exact:true})).toBeVisible()
 await expect(page.locator('.hero img')).toHaveJSProperty('complete',true)
 expect(requests.some(u=>/\/chunks\/(pdf|Editor|MarkdownEditor)\.|pdf\.worker|codemirror/i.test(u))).toBe(false)
 await fs.mkdir('screenshots',{recursive:true})
 await page.screenshot({path:'screenshots/home-light.png',fullPage:true})
 await page.getByRole('button',{name:/主题/}).click();await page.getByRole('button',{name:/主题/}).click()
 await expect(page.locator('html')).toHaveClass('dark');await page.reload();await expect(page.locator('html')).toHaveClass('dark')
 await page.screenshot({path:'screenshots/home-dark.png',fullPage:true})
 await page.keyboard.press('Control+k');await page.getByRole('textbox',{name:'搜索关键词'}).fill('PDF')
 await expect(page.locator('.search-results a').first()).toBeVisible();await page.keyboard.press('Escape')
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'screenshots/home-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('link',{name:'文章',exact:true}).click();await page.getByRole('button',{name:/阅读 1/}).click()
 await expect(page.locator('.post-list .post-row')).toHaveCount(1)
})
test('editor auto-saves, imports folder ZIP with GIF, exports and restores',async({page})=>{
 await page.goto('/editor.html')
 await page.getByLabel('标题',{exact:true}).fill('Browser draft')
 await page.getByLabel('文章地址',{exact:true}).fill('browser-draft')
 await page.locator('.cm-content').fill('## Editing works\n\nA paragraph.')
 await expect(page.locator('.save-note')).toContainText('已保存')
 await page.reload();await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Browser draft')
 await expect(page.frameLocator('iframe[title="文章实时预览"]').getByRole('heading',{name:'Editing works'})).toBeVisible()
 const gif=new Uint8Array(await fs.readFile(fixture('animated.gif')))
 const zip=zipSync({'pack/note.md':strToU8('---\ntitle: Imported GIF\ndate: 2026-09-22\ntags: [demo]\n---\n\n![motion](images/animated.gif)'),'pack/images/animated.gif':gif})
 await page.getByTestId('import-md').setInputFiles({name:'bundle.zip',mimeType:'application/zip',buffer:Buffer.from(zip)})
 await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Imported GIF')
 const img=page.frameLocator('iframe[title="文章实时预览"]').locator('img')
 await expect(img).toBeVisible();await expect(img).toHaveJSProperty('naturalWidth',40)
 await page.getByLabel('文章地址',{exact:true}).fill('gif-note')
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下载文章包',exact:true}).click()
 const download=await downloadPromise;expect(download.suggestedFilename()).toBe('gif-note.zip');const archive=await download.path();await page.getByTestId('import-md').setInputFiles({name:'roundtrip.zip',mimeType:'application/zip',buffer:await fs.readFile(archive!)});await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Imported GIF');await expect(page.frameLocator('iframe[title="文章实时预览"]').locator('img')).toHaveJSProperty('naturalWidth',40)
 await page.getByTestId('token').fill('fake-never-store-this')
 await page.getByRole('button',{name:'保存草稿',exact:true}).click()
 const storage=await page.evaluate(()=>JSON.stringify(localStorage));expect(storage).not.toContain('fake-never-store-this')
 await page.reload();await expect(page.getByTestId('token')).toHaveValue('')
 await page.screenshot({path:'screenshots/editor-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'预览',exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('preview isolates hostile HTML and Vue expressions',async({page})=>{
 await page.goto('/editor.html')
 await page.locator('.cm-content').fill('<script>parent.xssProbe=1</script>\n\n<img src=x onerror="parent.xssProbe=2">\n\n{{ parent.localStorage }}\n\n[bad](javascript:alert(1))')
 const body=page.frameLocator('iframe[title="文章实时预览"]').locator('body')
 await expect(body).toContainText('<script>parent.xssProbe=1</script>')
 expect(await page.evaluate(()=>(window as any).xssProbe)).toBeUndefined()
 await expect(body.locator('script,img[onerror],a[href^="javascript"]')).toHaveCount(0)
 expect(await page.locator('iframe[title="文章实时预览"]').getAttribute('sandbox')).toBe('')
})
for(const [name,kind] of [['text.pdf','文字'],['scan.pdf','图像'],['mixed.pdf','图像'],['columns.pdf','复杂布局']]){
 test('PDF conversion '+name,async({page})=>{
  await page.goto('/editor.html');await page.getByText('导入 PDF',{exact:true}).click()
  await page.getByTestId('import-pdf').setInputFiles(fixture(name))
  await expect(page.locator('.pdf-report')).toContainText(kind,{timeout:60000})
  await expect(page.getByRole('link',{name:'打开原 PDF 对照'})).toBeVisible()
  if(name==='text.pdf'||name==='mixed.pdf'){
    await expect(page.locator('.cm-content')).toContainText('PDF text sample')
    await expect(page.locator('.asset-name')).toContainText(['original.pdf','page-1-image-1.png'])
    await expect(page.frameLocator('iframe[title="文章实时预览"]').locator('img').first()).toBeVisible()
  }
  if(name==='scan.pdf')await expect(page.locator('.cm-content')).not.toContainText('This text exists only as pixels')
  if(name==='mixed.pdf'){await expect(page.locator('.pdf-report>li')).toHaveCount(2);await page.screenshot({path:'screenshots/pdf-mixed.png',fullPage:true})}
 })
}
test('PDF original-only and print layout',async({page})=>{
 await page.goto('/editor.html');await page.getByText('导入 PDF',{exact:true}).click();await page.getByLabel('保留原 PDF，不转换文字').check()
 await page.getByTestId('import-pdf').setInputFiles(fixture('scan.pdf'))
 await expect(page.getByLabel('标题',{exact:true})).toHaveValue('scan')
 await expect(page.locator('.asset-row')).toHaveCount(1)
 await page.goto('/posts/start-here.html')
 await page.emulateMedia({media:'print'})
 await expect(page.locator('.site-header')).toBeHidden();await expect(page.locator('.print-button')).toBeHidden()
 await expect(page.locator('.prose table')).toBeVisible()
 await page.pdf({path:'screenshots/article-print.pdf',format:'A4',printBackground:true})
 await page.screenshot({path:'screenshots/article-print.png',fullPage:true})
})

