import {test,expect} from '@playwright/test'
test('owner deletion requires confirmation and preserves the local draft',async({page})=>{
 let writes=0,owner=false
 await page.route('https://api.github.com/**',async route=>{
  const p=new URL(route.request().url()).pathname.replace('/repos/print-happy/personal-learning-blog','')
  const json=(v:any)=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(v)})
  if(route.request().method()!=='GET')writes++
  if(p==='/user')return json({id:owner?1:2})
  if(p==='')return json({owner:{id:1,type:'User'},permissions:{push:true}})
  if(p.startsWith('/git/ref/'))return json({object:{sha:'base'}})
  if(p==='/git/commits/base')return json({tree:{sha:'tree'}})
  if(p==='/git/trees/tree')return json({tree:[{path:'content/posts/note/index.md',sha:'article',mode:'100644',type:'blob'}]})
  if(p==='/git/blobs/article')return json({encoding:'base64',content:Buffer.from('---\ntitle: Owner note\ndate: 2026-09-22\ntags: []\n---\nSaved body').toString('base64'),size:90})
  if(p==='/git/trees')return json({sha:'next'})
  if(p==='/git/commits')return json({sha:'commit'})
  if(p.startsWith('/git/refs/'))return json({})
  if(p.includes('/actions/workflows/'))return json({workflow_runs:[]})
  throw Error(p)
 })
 await page.goto('/personal-learning-blog/editor.html')
 await page.getByTestId('token').fill('mock-owner-token')
 await page.getByText('管理已有文章',{exact:true}).click()
 const remove=page.getByRole('button',{name:'删除已发布文章',exact:true})
 await expect(remove).toBeDisabled()
 await page.getByLabel('远端文章地址').fill('note')
 await page.getByRole('button',{name:'载入远端文章'}).click()
 await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Owner note')
 await remove.click();await expect(page.getByRole('alert')).toContainText('所有者');expect(writes).toBe(0)
 owner=true;page.once('dialog',d=>d.dismiss());await remove.click();await expect(remove).toBeEnabled();expect(writes).toBe(0)
 page.once('dialog',async d=>{expect(d.message()).toContain('Owner note');expect(d.message()).toContain('PDF');await d.accept()})
 await remove.click();await expect(page.getByRole('button',{name:'刷新发布状态'})).toBeVisible();expect(writes).toBe(3)
 await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Owner note')
 await page.reload();await expect(page.getByLabel('标题',{exact:true})).toHaveValue('Owner note');await expect(page.getByTestId('token')).toHaveValue('')
})
